### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by nicola** [linkeddata/node-webid#3]
From @deiu, https://github.com/linkeddata/ldnode/issues/101

```
TypeError: Cannot call method 'replace' of undefined
  at new VerificationAgent (/devel/github.com/linkeddata/ldnode/node_modules/webid/index.js:21:23)
  at loginHandler (/devel/github.com/linkeddata/ldnode/login.js:20:30)
  at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:312:13)
  at /devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:280:7
  at param (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:349:14)
  at param (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:365:14)
  at Function.process_params (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:410:3)
  at next (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:271:10)
  at /devel/github.com/linkeddata/ldnode/index.js:125:24
```

**Comment by nicola** [comment]
So, this happens when no subjectAltName that matches `/URI:([^, ]+)/g` is passed, what should be the default behavior?

**Comment by deiu** [comment]
If there is no URI: in the subjectAltName, it should just fail to authenticate. It should also log the reason (missing WebID in SAN field).

**Comment by nicola** [comment]
perfect, thanks

**Comment by deiu** [comment]
BTW, the type of the URI is not concatenated to the actual value. It's encoded using ASN.1. I'm not sure how node handles the decoding, so you might have to double check.

**Comment by nicola** [comment]
Fixed in latest
